# Generated by Django 5.2.6 on 2025-10-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement', '0001_initial'),
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssummary',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summaries', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='dailyanalytics',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hostels.hostel'),
        ),
    ]
