# Generated by Django 5.2.6 on 2025-10-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement', '0001_initial'),
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
