# Generated by Django 5.2.6 on 2025-10-12 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagement', '0002_initial'),
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelanalytics',
            name='hostel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_reports', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='search_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engagement.searchhistory'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticssummary',
            unique_together={('hostel', 'period_type', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together={('hostel', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'hostel')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'hostel')},
        ),
    ]
