# Generated by Django 5.2.6 on 2025-10-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_response',
            field=models.TextField(blank=True, help_text="Hostel owner's response to the review", null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the owner responded', null=True),
        ),
    ]
