# Generated by Django 5.2.6 on 2025-10-02 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_initial'),
        ('hostels', '0003_room_media_alter_room_hostel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('call', 'Call'), ('whatsapp', 'WhatsApp')], default='view', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'hostel')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'hostel')},
        ),
    ]
