# Generated by Django 5.2.6 on 2025-10-12 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_alter_review_hostel_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0, message='Latitude must be between -90 and 90 degrees'), django.core.validators.MaxValueValidator(90.0, message='Latitude must be between -90 and 90 degrees')]),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0, message='Longitude must be between -180 and 180 degrees'), django.core.validators.MaxValueValidator(180.0, message='Longitude must be between -180 and 180 degrees')]),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Maximum price cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Minimum price cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='radius',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Search radius must be at least 1 kilometer'), django.core.validators.MaxValueValidator(50, message='Search radius cannot exceed 50 kilometers')]),
        ),
    ]
