# Generated by Django 5.2.6 on 2025-10-12 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_alter_searchhistory_gender_preference_and_more'),
        ('hostels', '0004_alter_room_available_capacity_alter_room_facilities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='interactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='interactionlog',
            name='search_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engagement.searchhistory'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='hostels.hostel'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='hostels.hostel'),
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'Viewed Hostel'), ('whatsapp', 'WhatsApp Contact'), ('call', 'Phone Call'), ('search', 'Search Result Click')], max_length=10),
        ),
    ]
