# Generated by Django 5.2.6 on 2025-10-12 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_alter_favorite_options_alter_interactionlog_options_and_more'),
        ('hostels', '0004_alter_room_available_capacity_alter_room_facilities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionlog',
            name='safety_confirmed',
            field=models.BooleanField(default=False, help_text='Whether the user confirmed the safety modal (required for female users)'),
        ),
        migrations.CreateModel(
            name='HostelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0)),
                ('total_contacts', models.IntegerField(default=0)),
                ('total_favorites', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='hostels.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Fake Listing'), ('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('fraud', 'Fraud Attempt'), ('incorrect_info', 'Incorrect Information'), ('safety', 'Safety Concern'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(help_text='Additional details about the report')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hostels.hostel')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_views', models.IntegerField(default=0)),
                ('total_contacts', models.IntegerField(default=0)),
                ('total_favorites', models.IntegerField(default=0)),
                ('total_searches', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summaries', to='hostels.hostel')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('hostel', 'period_type', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('contacts', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
                ('searches_appeared', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='hostels.hostel')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('hostel', 'date')},
            },
        ),
    ]
