# Generated by Django 5.2.6 on 2025-10-12 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0008_alter_report_user'),
        ('hostels', '0004_alter_room_available_capacity_alter_room_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_reports', to='hostels.hostel'),
        ),
    ]
