# Generated by Django 5.2.6 on 2025-10-13 18:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='cnic_image',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='cnic_back',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Back side of CNIC', max_length=255, null=True, verbose_name='cnic_back'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='cnic_front',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Front side of CNIC', max_length=255, null=True, verbose_name='cnic_front'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Detailed reason for rejection provided by admin', null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='utility_bill',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Utility bill or property document for location verification', max_length=255, null=True, verbose_name='utility_bill'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='room_images',
            field=models.JSONField(blank=True, help_text="List of {url, source, verified} objects where source is 'camera' or 'gallery'", null=True),
        ),
    ]
