# Generated by Django 5.2.6 on 2025-10-13 19:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_remove_verificationrequest_cnic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='passport_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Passport-size photo captured by camera', max_length=255, null=True, verbose_name='passport_photo'),
        ),
    ]
