# Generated by Django 5.2.6 on 2025-10-12 14:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('media', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('city', models.CharField(choices=[('karachi', 'Karachi'), ('lahore', 'Lahore'), ('islamabad', 'Islamabad'), ('multan', 'Multan'), ('bahawalpur', 'Bahawalpur'), ('rawalpindi', 'Rawalpindi'), ('faisalabad', 'Faisalabad'), ('peshawar', 'Peshawar'), ('quetta', 'Quetta')], default='lahore', max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('map_location', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('total_rooms', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('room_type', models.CharField(choices=[('shared', 'Shared Room'), ('ind', 'Independent Room')], default='shared', max_length=50)),
                ('total_capacity', models.PositiveIntegerField(help_text='Total number of beds in the room')),
                ('available_capacity', models.PositiveIntegerField(help_text='Number of beds currently available')),
                ('rent', models.DecimalField(decimal_places=2, help_text='Monthly rent per bed', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facilities', models.JSONField(blank=True, help_text='List of available facilities', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
