# Generated by Django 5.2.6 on 2025-10-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_room_media_alter_room_hostel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='beds_available',
            new_name='available_capacity',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='total_capacity',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='area',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='media',
        ),
        migrations.AddField(
            model_name='hostel',
            name='total_rooms',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('shared', 'Shared Room'), ('ind', 'Independent Room')], default='shared', max_length=50),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='city',
            field=models.CharField(choices=[('karachi', 'Karachi'), ('lahore', 'Lahore'), ('islamabad', 'Islamabad'), ('multan', 'Multan'), ('bahawalpur', 'Bahawalpur'), ('rawalpindi', 'Rawalpindi'), ('faisalabad', 'Faisalabad'), ('peshawar', 'Peshawar'), ('quetta', 'Quetta')], default='lahore', max_length=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='map_location',
            field=models.URLField(),
        ),
    ]
