# Generated by Django 5.2.6 on 2025-10-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_capacity',
            field=models.PositiveIntegerField(help_text='Number of beds currently available'),
        ),
        migrations.AlterField(
            model_name='room',
            name='facilities',
            field=models.JSONField(blank=True, help_text='List of available facilities', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent per bed', max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_capacity',
            field=models.PositiveIntegerField(help_text='Total number of beds in the room'),
        ),
    ]
