# Generated by Django 5.2.6 on 2025-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_rename_beds_available_room_available_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostel',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostel',
            name='map_location',
            field=models.URLField(blank=True, null=True),
        ),
    ]
