# Generated by Django 5.2.6 on 2025-10-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='map_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
