# Generated by Django 5.2.6 on 2025-10-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_alter_hostel_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
