// Mock data for hostels with complete details
export const dummyHostels = [
    {
        id: 1,
        name: "Sunshine Hostel",
        city: "Lahore",
        address: "123 Main Street, Gulberg III",
        totalRooms: 20,
        availableRooms: 5,
        occupiedRooms: 15,
        facilities: ["WiFi", "AC", "Parking", "Security", "Laundry", "Kitchen", "Meals", "CCTV"],
        gender: "male",
        rating: 4.5,
        reviewCount: 45,
        verified: true,
        verificationStatus: "approved",
        phone: "+92 300 1234567",
        email: "sunshine@example.com",
        description: "Modern hostel with excellent facilities in the heart of Gulberg. Perfect for students seeking a comfortable living experience with all modern amenities.",
        latitude: 31.5204,
        longitude: 74.3587,
        mapLocation: "https://goo.gl/maps/example1",
        images: [
            "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80",
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"
        ],
        videoUrl: "https://www.youtube.com/watch?v=example",
        documents: [
            { name: "CNIC", url: "cnic.pdf", uploadedAt: "2025-01-10" },
            { name: "Business License", url: "license.pdf", uploadedAt: "2025-01-10" },
            { name: "Utility Bill", url: "utility_bill.pdf", uploadedAt: "2025-01-10" }
        ],
        interactions: 150,
        disabled: false,
        createdAt: "2025-01-15",
        updatedAt: "2025-03-20",
    },
    {
        id: 2,
        name: "Green Valley Hostel",
        city: "Islamabad",
        address: "456 Park Road, F-6",
        totalRooms: 15,
        availableRooms: 3,
        occupiedRooms: 12,
        facilities: ["WiFi", "Security", "Gym", "Common Room", "Study Area", "CCTV"],
        gender: "female",
        rating: 4.2,
        reviewCount: 32,
        verified: true,
        verificationStatus: "approved",
        phone: "+92 300 7654321",
        email: "greenvalley@example.com",
        description: "Peaceful hostel for female students in a secure neighborhood with excellent study facilities.",
        latitude: 33.7294,
        longitude: 73.0931,
        mapLocation: "https://goo.gl/maps/example2",
        images: [
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"
        ],
        videoUrl: "",
        documents: [
            { name: "CNIC", url: "cnic2.pdf", uploadedAt: "2025-02-01" },
            { name: "Business License", url: "license2.pdf", uploadedAt: "2025-02-01" }
        ],
        interactions: 98,
        disabled: false,
        createdAt: "2025-02-10",
        updatedAt: "2025-03-15",
    },
    {
        id: 3,
        name: "City Center Hostel",
        city: "Karachi",
        address: "789 Clifton Block 5",
        totalRooms: 30,
        availableRooms: 10,
        occupiedRooms: 20,
        facilities: ["WiFi", "AC", "Security", "24/7 Water", "Backup Generator", "Laundry"],
        gender: "male",
        rating: 4.7,
        reviewCount: 68,
        verified: false,
        verificationStatus: "pending",
        phone: "+92 300 9876543",
        email: "citycenter@example.com",
        description: "Premium hostel with modern amenities near universities and shopping centers.",
        latitude: 24.8607,
        longitude: 67.0011,
        mapLocation: "https://goo.gl/maps/example3",
        images: [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
            "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"
        ],
        videoUrl: "https://www.youtube.com/watch?v=example3",
        documents: [
            { name: "CNIC", url: "cnic3.pdf", uploadedAt: "2025-03-01" }
        ],
        interactions: 210,
        disabled: false,
        createdAt: "2025-03-05",
        updatedAt: "2025-03-10",
    },
    {
        id: 4,
        name: "Student Paradise",
        city: "Multan",
        address: "321 University Road",
        totalRooms: 12,
        availableRooms: 0,
        occupiedRooms: 12,
        facilities: ["WiFi", "Study Room", "Security", "Kitchen", "Common Area"],
        gender: "female",
        rating: 4.0,
        reviewCount: 25,
        verified: true,
        verificationStatus: "approved",
        phone: "+92 300 1122334",
        email: "studentparadise@example.com",
        description: "Affordable hostel for female students near the university campus.",
        latitude: 30.1575,
        longitude: 71.5249,
        mapLocation: "https://goo.gl/maps/example4",
        images: [
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
            "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80"
        ],
        videoUrl: "",
        documents: [
            { name: "CNIC", url: "cnic4.pdf", uploadedAt: "2025-01-15" },
            { name: "Business License", url: "license4.pdf", uploadedAt: "2025-01-15" }
        ],
        interactions: 75,
        disabled: false,
        createdAt: "2025-01-20",
        updatedAt: "2025-02-28",
    },
];

// Room facilities options
export const roomFacilitiesOptions = [
    "AC", "WiFi", "Attached Bath", "Study Table", "Wardrobe",
    "Balcony", "Mini Fridge", "TV", "Geyser", "Fan"
];

// Hostel facilities options
export const hostelFacilitiesOptions = [
    "WiFi", "AC", "Parking", "Security", "Laundry", "Kitchen",
    "Meals", "CCTV", "Gym", "Common Room", "Study Area",
    "24/7 Water", "Backup Generator", "Garden"
];

export const dummyRooms = [
    {
        id: 1,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        roomNumber: "101",
        type: "shared",
        capacity: 4,
        availableBeds: 2,
        occupiedBeds: 2,
        rent: 15000,
        deposit: 30000,
        facilities: ["AC", "WiFi", "Attached Bath", "Study Table"],
        images: [
            "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
            "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"
        ],
        status: "available",
        floor: 1,
        description: "Spacious room with modern furnishings and excellent ventilation",
        createdAt: "2025-01-15",
        updatedAt: "2025-03-18",
    },
    {
        id: 2,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        roomNumber: "102",
        type: "shared",
        capacity: 3,
        availableBeds: 0,
        occupiedBeds: 3,
        rent: 18000,
        deposit: 36000,
        facilities: ["AC", "WiFi", "Attached Bath", "Study Table", "Balcony"],
        images: [
            "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80",
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80"
        ],
        status: "occupied",
        floor: 1,
        description: "Comfortable room with balcony view",
        createdAt: "2025-01-15",
        updatedAt: "2025-03-15",
    },
    {
        id: 3,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        roomNumber: "201",
        type: "single",
        capacity: 1,
        availableBeds: 1,
        occupiedBeds: 0,
        rent: 25000,
        deposit: 50000,
        facilities: ["AC", "WiFi", "Attached Bath", "Study Table", "Wardrobe", "Mini Fridge"],
        images: [
            "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"
        ],
        status: "available",
        floor: 2,
        description: "Private room for single occupancy with premium amenities",
        createdAt: "2025-01-15",
        updatedAt: "2025-03-20",
    },
    {
        id: 4,
        hostelId: 2,
        hostelName: "Green Valley Hostel",
        roomNumber: "G01",
        type: "shared",
        capacity: 2,
        availableBeds: 1,
        occupiedBeds: 1,
        rent: 20000,
        deposit: 40000,
        facilities: ["AC", "WiFi", "Attached Bath", "Study Table"],
        images: [
            "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80",
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80"
        ],
        status: "available",
        floor: 0,
        description: "Ground floor room with garden access",
        createdAt: "2025-02-10",
        updatedAt: "2025-03-10",
    },
    {
        id: 5,
        hostelId: 2,
        hostelName: "Green Valley Hostel",
        roomNumber: "G02",
        type: "shared",
        capacity: 4,
        availableBeds: 0,
        occupiedBeds: 4,
        rent: 16000,
        deposit: 32000,
        facilities: ["AC", "WiFi", "Attached Bath"],
        images: [
            "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"
        ],
        status: "occupied",
        floor: 0,
        description: "Economical shared room",
        createdAt: "2025-02-10",
        updatedAt: "2025-03-05",
    },
    {
        id: 6,
        hostelId: 3,
        hostelName: "City Center Hostel",
        roomNumber: "301",
        type: "single",
        capacity: 1,
        availableBeds: 0,
        occupiedBeds: 1,
        rent: 30000,
        deposit: 60000,
        facilities: ["AC", "WiFi", "Attached Bath", "Study Table", "Wardrobe", "Mini Fridge", "TV"],
        images: [
            "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
            "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80"
        ],
        status: "maintenance",
        floor: 3,
        description: "Premium single room with all amenities",
        createdAt: "2025-03-05",
        updatedAt: "2025-03-18",
    },
];

export const dummyBookings = [
    {
        id: 1,
        studentName: "Ali Khan",
        email: "ali@example.com",
        phone: "+92 300 1234567",
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        roomId: 1,
        roomNumber: "101",
        bookingDate: "2025-01-20",
        moveInDate: "2025-02-01",
        status: "pending",
        rent: 15000,
        deposit: 30000,
        duration: "6 months",
        notes: "Prefer ground floor room",
    },
    {
        id: 2,
        studentName: "Sara Ahmed",
        email: "sara@example.com",
        phone: "+92 300 7654321",
        hostelId: 2,
        hostelName: "Green Valley Hostel",
        roomId: 4,
        roomNumber: "G01",
        bookingDate: "2025-02-15",
        moveInDate: "2025-03-01",
        status: "approved",
        rent: 20000,
        deposit: 40000,
        duration: "12 months",
        notes: "",
    },
    {
        id: 3,
        studentName: "Usman Raza",
        email: "usman@example.com",
        phone: "+92 300 9876543",
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        roomId: 3,
        roomNumber: "201",
        bookingDate: "2025-03-10",
        moveInDate: "2025-04-01",
        status: "rejected",
        rent: 25000,
        deposit: 50000,
        duration: "6 months",
        notes: "Looking for a quiet room",
    },
    {
        id: 4,
        studentName: "Fatima Malik",
        email: "fatima@example.com",
        phone: "+92 300 1122334",
        hostelId: 2,
        hostelName: "Green Valley Hostel",
        roomId: 4,
        roomNumber: "G01",
        bookingDate: "2025-03-15",
        moveInDate: "2025-04-15",
        status: "pending",
        rent: 20000,
        deposit: 40000,
        duration: "12 months",
        notes: "Urgent requirement",
    },
    {
        id: 5,
        studentName: "Ahmed Hassan",
        email: "ahmed@example.com",
        phone: "+92 300 5544332",
        hostelId: 3,
        hostelName: "City Center Hostel",
        roomId: 6,
        roomNumber: "301",
        bookingDate: "2025-03-20",
        moveInDate: "2025-05-01",
        status: "approved",
        rent: 30000,
        deposit: 60000,
        duration: "6 months",
        notes: "Professional student",
    },
];

// Reviews data
export const dummyReviews = [
    {
        id: 1,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        studentName: "Ali Khan",
        studentEmail: "ali@example.com",
        rating: 5,
        comment: "Excellent hostel with great facilities. Staff is very cooperative and rooms are clean.",
        createdAt: "2025-03-15",
        ownerResponse: "Thank you for your kind words! We're glad you enjoyed your stay.",
        respondedAt: "2025-03-16",
    },
    {
        id: 2,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        studentName: "Sara Ahmed",
        studentEmail: "sara@example.com",
        rating: 4,
        comment: "Good hostel but WiFi could be faster. Otherwise everything is perfect.",
        createdAt: "2025-03-10",
        ownerResponse: "",
        respondedAt: null,
    },
    {
        id: 3,
        hostelId: 2,
        hostelName: "Green Valley Hostel",
        studentName: "Ayesha Khan",
        studentEmail: "ayesha@example.com",
        rating: 5,
        comment: "Perfect place for female students. Very safe and secure environment.",
        createdAt: "2025-03-12",
        ownerResponse: "Thank you! Your safety and comfort is our priority.",
        respondedAt: "2025-03-13",
    },
    {
        id: 4,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        studentName: "Hassan Ali",
        studentEmail: "hassan@example.com",
        rating: 3,
        comment: "Decent place but a bit expensive for the facilities provided.",
        createdAt: "2025-03-08",
        ownerResponse: "",
        respondedAt: null,
    },
];

// Reports/Complaints data
export const dummyReports = [
    {
        id: 1,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        studentName: "Anonymous",
        studentEmail: "student1@example.com",
        reason: "Water supply issue in room 102",
        description: "Water is not available in the morning hours. This has been happening for the past week.",
        status: "pending",
        createdAt: "2025-03-18",
        resolvedAt: null,
        adminNotes: "",
    },
    {
        id: 2,
        hostelId: 1,
        hostelName: "Sunshine Hostel",
        studentName: "Anonymous",
        studentEmail: "student2@example.com",
        reason: "Noise complaint",
        description: "Too much noise from the common area late at night.",
        status: "resolved",
        createdAt: "2025-03-10",
        resolvedAt: "2025-03-12",
        adminNotes: "Owner has implemented quiet hours policy.",
    },
    {
        id: 3,
        hostelId: 3,
        hostelName: "City Center Hostel",
        studentName: "Anonymous",
        studentEmail: "student3@example.com",
        reason: "Cleanliness issue",
        description: "Washrooms are not cleaned regularly.",
        status: "under_review",
        createdAt: "2025-03-15",
        resolvedAt: null,
        adminNotes: "Investigating the complaint.",
    },
];

// Verification requests
export const dummyVerificationRequests = [
    {
        id: 1,
        hostelId: 3,
        hostelName: "City Center Hostel",
        status: "pending",
        documents: [
            { name: "CNIC", url: "cnic3.pdf", uploadedAt: "2025-03-01" }
        ],
        submittedAt: "2025-03-05",
        reviewedAt: null,
        adminNotes: "",
    },
];

// Statistics data
export const dummyStats = {
    totalHostels: 4,
    totalRooms: 77,
    totalBookings: 5,
    pendingBookings: 2,
    approvedBookings: 2,
    rejectedBookings: 1,
    occupancyRate: 75,
    totalRevenue: 350000,
    monthlyRevenue: 150000,
    totalInteractions: 533,
    avgRating: 4.3,
    totalReviews: 170,
    totalReports: 3,
};

// Booking trends data for charts
export const bookingTrends = [
    { month: "Jan", bookings: 12 },
    { month: "Feb", bookings: 15 },
    { month: "Mar", bookings: 18 },
    { month: "Apr", bookings: 22 },
    { month: "May", bookings: 19 },
    { month: "Jun", bookings: 25 },
];

// Revenue trends data
export const revenueTrends = [
    { month: "Jan", revenue: 120000 },
    { month: "Feb", revenue: 135000 },
    { month: "Mar", revenue: 150000 },
    { month: "Apr", revenue: 165000 },
    { month: "May", revenue: 142000 },
    { month: "Jun", revenue: 180000 },
];

// Interaction trends
export const interactionTrends = [
    { month: "Jan", calls: 45, whatsapp: 32, views: 120 },
    { month: "Feb", calls: 52, whatsapp: 38, views: 145 },
    { month: "Mar", calls: 60, whatsapp: 45, views: 178 },
    { month: "Apr", calls: 55, whatsapp: 42, views: 165 },
    { month: "May", calls: 65, whatsapp: 50, views: 190 },
    { month: "Jun", calls: 70, whatsapp: 55, views: 210 },
];