# Generated by Django 5.2.6 on 2025-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
