# Generated by Django 5.2.6 on 2025-10-11 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Pakistani mobile number starting with +923 or 03', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Pakistani number. Format: +923XXXXXXXXX or 03XXXXXXXXX', regex='^(\\+92|0)?3\\d{9}$')]),
        ),
    ]
